# LISTS
PLIST_BASE_CASE = 1
PLIST_TAIL = 2
PLIST_TAIL_WITH_SEP = 3

# GENERAL
PLIST_DATA = 1
PTYPE_DATA = 1

# p_main_program
PMAIN_PROGRAM_STREAM_TYPES = 1
PMAIN_PROGRAM_EVENT_SOURCES = 2
PMAIN_PROGRAM_ARBITER = 3
PMAIN_PROGRAM_MONITOR = 4

# p_stream_type
PSTREAM_TYPE_NAME = 3
PSTREAM_TYPE_EVENT_LIST = 5

PPSTREAM_TYPE_NAME = 1
PPSTREAM_TYPE_EVENT_LIST = 2

# p_event_declaration
PEVENT_NAME = 1
PEVENT_PARAMS_LIST = 3

PPEVENT_NAME = 1
PPEVENT_PARAMS_LIST = 2

# p_field_declaration
PFIELD_NAME = 1
PFIELD_TYPE = 3

PPFIELD_NAME = 1
PPFIELD_TYPE = 2

# p_event_source
PEVENT_SOURCE_NAME = 3
PEVENT_SOURCE_INPUT_TYPE = 5
PEVENT_CONN_KIND = 7
PEVENT_SOURCE_OUTPUT_TYPE = 8
PEVENT_SOURCE_PERF_LAYER_LIST = 10

PPEVENT_SOURCE_NAME = 1
PPEVENT_SOURCE_INPUT_TYPE = 2
PPEVENT_CONN_KIND = 3
PPEVENT_SOURCE_OUTPUT_TYPE = 4
PPEVENT_SOURCE_PERF_LAYER_LIST = 5

# p_performance_layer_rule
PPERF_LAYER_EVENT = 2
PPERF_LAYER_EV_ARGS = 4
PPERF_LAYER_PERF_MATCH = 6

PPPERF_LAYER_EVENT = 1
PPPERF_LAYER_EV_ARGS = 2
PPPERF_LAYER_PERF_MATCH = 3

# p_performance_match
PPERF_MATCH_ACTION = 1
PPERF_MATCH_EXPRESSION = 3
PPERF_MATCH_TRUE_PART = 6
PPERF_MATCH_FALSE_PART = 8

PPPERF_MATCH_ACTION = 1
PPPERF_MATCH_EXPRESSION = 1
PPPERF_MATCH_TRUE_PART = 2
PPPERF_MATCH_FALSE_PART = 3

#  p_performance_action
PPERF_ACTION_DROP = 1
PPERF_ACTION_FORWARD_EVENT = 2
PPERF_ACTION_FORWARD_EXPRS = 4

PPPERF_ACTION_DROP = 1
PPPERF_ACTION_FORWARD_EVENT = 1
PPPERF_ACTION_FORWARD_EXPRS = 2

# p_connection_kind
PCONN_KIND_NAME = 1
PCONN_KIND_INT = 3

PPCONN_KIND_NAME = 1
PPCONN_KIND_INT = 2

#  p_arbiter_definition
ARBITER_OUTPUT_TYPE = 3
ARBITER_RULE_SET_LIST = 5

PPARBITER_OUTPUT_TYPE = 1
PPARBITER_RULE_SET_LIST = 2

# p_arbiter_rule_set
PARB_RULE_SET_NAME = 3
PARB_RULE_LIST = 5

PPARB_RULE_SET_NAME = 1
PPARB_RULE_LIST = 2

# p_arbiter_rule
PARB_RULE_LIST_BUFF_EXPR = 2
PARB_RULE_CONDITION_CODE = 4
PARB_RULE_STMT_LIST = 5

PPARB_RULE_LIST_BUFF_EXPR = 1
PPARB_RULE_CONDITION_CODE = 2
PPARB_RULE_STMT_LIST = 3

# p_buffer_match_exp
PBUFFER_MATCH_EV_NAME = 1
PBUFFER_MATCH_ARG1 = 3
PBUFFER_MATCH_ARG2 = 4
PBUFFER_MATCH_ARG3 = 5

PPBUFFER_MATCH_EV_NAME = 1
PPBUFFER_MATCH_ARG1 = 2
PPBUFFER_MATCH_ARG2 = 3
PPBUFFER_MATCH_ARG3 = 4

# p_list_event_calls
PLIST_EV_CALL_EV_NAME = 1
PLIST_EV_CALL_EV_PARAMS = 3
PLIST_EV_CALL_TAIL = 5

PPLIST_EV_CALL_EV_NAME = 1
PPLIST_EV_CALL_EV_PARAMS = 2
PPLIST_EV_CALL_TAIL = 3

# p_ccode_statement_list
PCODE_STMT_LIST_TOKEN1 = 1
PCODE_STMT_LIST_TOKEN2 = 2
PCODE_STMT_LIST_TOKEN3 = 3


#  p_arbiter_rule_stmt
PARB_RULE_STMT_YIELD_EVENT = 2
PARB_RULE_STMT_YIELD_EXPRS = 4
PARB_RULE_STMT_DROP_INT = 2
PARB_RULE_STMT_DROP_EV_SOURCE = 4
PARB_RULE_STMT_SWITCH_ARB_RULE = 3

PPARB_RULE_STMT_YIELD_EVENT = 1
PPARB_RULE_STMT_YIELD_EXPRS = 2
PPARB_RULE_STMT_DROP_INT = 1
PPARB_RULE_STMT_DROP_EV_SOURCE = 2
PPARB_RULE_STMT_SWITCH_ARB_RULE = 1

# p_monitor_definition
PMONITOR_RULE_LIST = 3

PPMONITOR_RULE_LIST = 1

# p_monitor_rule
PMONITOR_RULE_EV_NAME = 2
PMONITOR_RULE_EV_ARGS = 4
PMONITOR_RULE_EXPR = 7
PMONITOR_RULE_CODE = 8

PPMONITOR_RULE_EV_NAME = 1
PPMONITOR_RULE_EV_ARGS = 2
PPMONITOR_RULE_EXPR = 3
PPMONITOR_RULE_CODE = 4

# p_type
PTYPE_NAME = 1


